version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: 
          name: iOS Test
          command: xcodebuild test -workspace Stylist.xcworkspace -scheme Stylist-iOS -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty
      - run: 
          name: tvOS Test
          command: xcodebuild test -workspace Stylist.xcworkspace -scheme Stylist-tvOS -sdk appletvsimulator -destination "name=Apple TV 4K" | xcpretty
